# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

# install for maven
orbs:
  maven: circleci/maven@1.4.1


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java17
